// <auto-generated />
using HotelListing.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.Api.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    [Migration("20221217095024_seedingdatabase")]
    partial class seedingdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelListing.Api.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "pakistan",
                            ShortName = "pak"
                        },
                        new
                        {
                            Id = 2,
                            Name = "japan",
                            ShortName = "Jap"
                        },
                        new
                        {
                            Id = 3,
                            Name = "india",
                            ShortName = "Ind"
                        },
                        new
                        {
                            Id = 4,
                            Name = "srilanka",
                            ShortName = "SL"
                        });
                });

            modelBuilder.Entity("HotelListing.Api.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "xxxx",
                            CountryId = 3,
                            Name = "Trident",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "yyyy",
                            CountryId = 2,
                            Name = "sangham",
                            Rating = 3.3999999999999999
                        },
                        new
                        {
                            Id = 3,
                            Address = "zzzz",
                            CountryId = 2,
                            Name = "aravindo",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 4,
                            Address = "xxxx",
                            CountryId = 3,
                            Name = "tension",
                            Rating = 1.3999999999999999
                        },
                        new
                        {
                            Id = 5,
                            Address = "oooo",
                            CountryId = 4,
                            Name = "non-Sense",
                            Rating = 3.2999999999999998
                        },
                        new
                        {
                            Id = 6,
                            Address = "pppp",
                            CountryId = 2,
                            Name = "tim tin",
                            Rating = 3.7999999999999998
                        });
                });

            modelBuilder.Entity("HotelListing.Api.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Api.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.Api.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
